"""添加messagemodel

Revision ID: 1b553e35ca73
Revises: 62ce6764513e
Create Date: 2020-10-14 14:49:38.598823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b553e35ca73'
down_revision = '62ce6764513e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True, comment='姓名'),
    sa.Column('tel', sa.String(length=128), nullable=True, comment='联系方式'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮件'),
    sa.Column('content', sa.Text(length=2048), nullable=True, comment='留言内容'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
