"""修改文章model

Revision ID: 287ec0e989fe
Revises: 8aa3f38ee32a
Create Date: 2020-10-08 20:07:56.884221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '287ec0e989fe'
down_revision = '8aa3f38ee32a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('pic', sa.String(length=256), nullable=True, comment='文章图片'))
    op.drop_column('article', 'is_show')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('is_show', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否展示'))
    op.drop_column('article', 'pic')
    # ### end Alembic commands ###
