"""修改资源model

Revision ID: 8aa3f38ee32a
Revises: b3073030bac7
Create Date: 2020-10-06 21:12:33.051861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8aa3f38ee32a'
down_revision = 'b3073030bac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('creator_id', sa.String(length=64), nullable=False, comment='创建者用户ID'))
    op.add_column('employee', sa.Column('user_id', sa.String(length=64), nullable=False, comment='用户ID'))
    op.create_unique_constraint(None, 'employee', ['user_id'])
    op.add_column('resource', sa.Column('category', sa.String(length=64), nullable=True, comment='视频类别'))
    op.add_column('resource', sa.Column('cover_pic', sa.String(length=128), nullable=True, comment='视频封面'))
    op.add_column('resource', sa.Column('title', sa.String(length=128), nullable=True, comment='标题'))
    op.alter_column('resource', 'is_video',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否是视频',
               existing_comment='是否展示',
               existing_nullable=True)
    op.drop_column('resource', 'small_pic')
    op.drop_column('resource', 'video_category')
    op.drop_column('resource', 'is_show')
    op.drop_column('resource', 'video_cover_pic')
    op.drop_column('resource', 'full_pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('full_pic', mysql.VARCHAR(length=128), nullable=True, comment='完整图片'))
    op.add_column('resource', sa.Column('video_cover_pic', mysql.VARCHAR(length=128), nullable=True, comment='视频封面'))
    op.add_column('resource', sa.Column('is_show', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否展示'))
    op.add_column('resource', sa.Column('video_category', mysql.VARCHAR(length=64), nullable=True, comment='视频类别'))
    op.add_column('resource', sa.Column('small_pic', mysql.VARCHAR(length=128), nullable=True, comment='缩略图'))
    op.alter_column('resource', 'is_video',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否展示',
               existing_comment='是否是视频',
               existing_nullable=True)
    op.drop_column('resource', 'title')
    op.drop_column('resource', 'cover_pic')
    op.drop_column('resource', 'category')
    op.drop_constraint(None, 'employee', type_='unique')
    op.drop_column('employee', 'user_id')
    op.drop_column('employee', 'creator_id')
    # ### end Alembic commands ###
